name: Verify Helm Chart

on:
  workflow_call:
    inputs:
      kind_nodes:
        description: "List of kind node images to test"
        required: false
        default: '["kindest/node:v1.32.8", "kindest/node:v1.33.4"]'
        type: string

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kind_node: ${{ fromJSON(inputs.kind_nodes) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1
        with:
          version: v3.19.0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .ct.yaml )
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --config .ct.yaml

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1
        with:
          version: 'v0.29.0'
          node_image: ${{ matrix.kind_node }}

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --config .ct.yaml
